/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;

/**
 *
 * @author Brian
 */
public class Helper {

    public static final String HELP_GLOBAL = "Bienvenido al Sistema de INEGAS\n\n"
            + "A continuacion se listaran los comandos disponibles para la interacción con el sistema.\n"
            //1
           
            + "REGISTRARADMINISTRADOR \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Administrador \n"
            + "El comando que permite registrar un Administrador es: REGISTRARADMINISTRADOR \n"
            + "parametros: REGISTRARADMINISTRADOR [nombre, apellido, ci, telefono, correo]\n"
            + "\n"
            + "OBTENERADMINISTRADOR \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener Administrador \n"
            + "El comando que permite obtener los datos de un Administrador es: HELP_OBTENERADMINISTRADOR \n"
            + "parametros: OBTENERADMINISTRADOR [id_administrador]\n"
            + "\n"
            + "OBTENERADMINISTRADORES \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener todos los Administradores \n"
            + "El comando que permite obtener todos los Administradores es: OBTENERADMINISTRADORES \n"
            + "parametros: OBTENERADMINISTRADORES\n"
            + "\n"
            + "MODIFICARADMINISTRADOR \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Modificar Administrador \n"
            + "El comando que permite modificar un Administrador es: MODIFICARADMINISTRADOR \n"
            + "parametros: MODIFICARADMINISTRADOR [id, nombre, apellido, ci, telefono, correo]\n"
            + "\n"
            + "ELIMINARADMINISTRADOR \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Administrador \n"
            + "El comando que permite Eliminar un Administrador es: ELIMINARADMINISTRADOR \n"
            + "parametros: ELIMINARADMINISTRADOR [id_administrador]\n"
            + "\n"
            //3
            + "REGISTRARCLIENTE \n" 
            + ">>>> Usuarios Nuevos del Sistema y Administradores\n"
            + "Registrar Cliente \n"
            + "El comando que permite registrar un Cliente es: REGISTRARCLIENTE \n"
            + "parametros: REGISTRARCLIENTE [nombre, apellido, ci, telefono, correo]\n"
            + "\n"
            + "OBTENERCLIENTE \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener Cliente \n"
            + "El comando que permite obtener los datos de un Cliente es: OBTENERCLIENTE \n"
            + "parametros: OBTENERCLIENTE [id_cliente]\n"
            + "\n"
            + "OBTENERCLIENTES \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener todos los Clientes \n"
            + "El comando que permite obtener los datos de un Cliente es: OBTENERCLIENTES \n"
            + "parametros: OBTENERCLIENTES\n"
            + "\n"
            + "MODIFICARCLIENTE \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Modificar Cliente \n"
            + "El comando que permite modificar un Cliente es: MODIFICARCLIENTE \n"
            + "parametros: MODIFICARCLIENTE [id, nombre, apellido, ci, telefono, correo]\n"
            + "\n"
            + "ELIMINARCLIENTE \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Cliente \n"
            + "El comando que permite Eliminar un Cliente es: ELIMINARCLIENTE \n"
            + "parametros: ELIMINARCLIENTE [id_cliente]\n"
            + "\n"
        
            //6
            + "REGISTRARPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Programa \n"
            + "El comando que permite registrar un Programa es: REGISTRARPROGRAMA \n"
            + "parametros: REGISTRARPROGRAMA [nombre,presupuesto, version, edicion, tipo, fecha_ela, fecha_apro]\n"
            + "\n"
            + "OBTENERPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener Programa \n"
            + "El comando que permite obtener los datos de un Programa es: OBTENERPROGRAMA \n"
            + "parametros: OBTENERPROGRAMA [id_programa]\n"
            + "\n"
            + "OBTENERPROGRAMAS \n" 
            + ">>>> Todos los Usuarios del Sistema\n"
            + "Obtener Programas \n"
            + "El comando que permite obtener un listado de todos los Programa es: OBTENERPROGRAMAS \n"
            + "parametros: OBTENERPROGRAMAS\n"
            + "\n"
            + "MODIFICARPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Programa \n"
            + "El comando que permite modificar un Programa es: MODIFICARPROGRAMA \n"
            + "parametros: MODIFICARPROGRAMA [id, nombre,presupuesto, version, edicion, tipo, fecha_ela, fecha_apro]\n"
            + "\n"
            + "ELIMINARPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Programa \n"
            + "El comando que permite Eliminar un Programa es: ELIMINARPROGRAMA \n"
            + "parametros: ELIMINARPROGRAMA [id_programa]\n"
            + "\n"
            //7
            + "REGISTRARMODULO \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Modulo \n"
            + "El comando que permite registrar un Modulo es: REGISTRARMODULO \n"
            + "parametros: REGISTRARMODULO [nombre, sigla, descripcion, costo, horas_a, horas_i]\n"
            + "\n"
            + "OBTENERMODULO \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener Modulo \n"
            + "El comando que permite obtener los datos de un modulo es: OBTENERMODULO \n"
            + "parametros: OBTENERMODULO [id_modulo]\n"
            + "\n"
            + "OBTENERMODULOS \n" 
            + ">>>> Todos los Usuarios del Sistema\n"
            + "Obtener Modulo \n"
            + "El comando que permite obtener un listado de todos los Modulos es: OBTENERMODULOS\n"
            + "parametros: OBTENERMODULOS\n"
            + "\n"
            + "MODIFICARMODULO \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Modulo \n"
            + "El comando que permite modificar un Modulo es: MODIFICARMODULO \n"
            + "parametros: MODIFICARMODULO [id,nombre, sigla, descripcion, costo, horas_a, horas_i]\n"
            + "\n"
            + "ELIMINARMODULO \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Modulo \n"
            + "El comando que permite Eliminar un Modulo es: ELIMINARMODULO \n"
            + "parametros: ELIMINARMODULO [id_modulo]\n"
            + "\n"
          //
          
            + "REGISTRARMODULOSPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Modulos a un Programa \n"
            + "El comando que permite registrar los Modulos de un Programa es: REGISTRARMODULOSPROGRAMA \n"
            + "parametros: REGISTRARMODULOSPROGRAMA [id_programa, id_modulo]\n"
            + "\n"
            + "OBTENERMODULOSPROGRAMA \n" 
            + ">>>> Todos los Usuarios del Sistema\n"
            + "Obtener Modulos de un Programa\n"
            + "El comando que permite obtener un Listado de los Modulos de un Programa es: OBTENERMODULOSPROGRAMA \n"
            + "parametros: OBTENERMODULOSPROGRAMA [id_programa]\n"
            + "\n"
            + "ELIMINARMODULOPROGRAMA \n" + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Modulo de un Programa\n"
            + "El comando que permite Eliminar un Modulo de un Programa es: ELIMINARMODULOPROGRAMA \n"
            + "parametros: ELIMINARMODULOPROGRAMA [id]\n"
            + "\n"
            //11
            + "REGISTRAROFERTAPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Oferta de un Programa \n"
            + "El comando que permite registrar la Oferta de un Programa es: REGISTRAROFERTAPROGRAMA \n"
            + "parametros: REGISTRAROFERTAPROGRAMA [fecha_inicio, fecha_fin, descripcion, id_programa]\n"
            + "\n"
            + "OBTENEROFERTAPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener la Oferta de un Programa \n"
            + "El comando que permite obtener la Oferta de un Programa es: OBTENEROFERTAPROGRAMA \n"
            + "parametros: OBTENEROFERTAPROGRAMA [id_ofertaPrograma]\n"
            + "\n"
            + "OBTENEROFERTAPROGRAMAS \n" 
            + ">>>> Todos los Usuarios del Sistema\n"
            + "Obtener Ofertas de Programas\n"
            + "El comando que permite obtener las Ofertas de los Programas es: OBTENEROFERTAPROGRAMAS \n"
            + "parametros: OBTENEROFERTAPROGRAMAS\n"
            + "\n"
            + "MODIFICAROFERTAPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Modificar Oferta de un Programa \n"
            + "El comando que permite modificar la Oferta de un Programa es: MODIFICAROFERTAPROGRAMA \n"
            + "parametros: MODIFICAROFERTAPROGRAMA [id_ofertaPrograma,descripcion]\n"
            + "\n"
            + "ELIMINAROFERTAPROGRAMA \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Oferta de un Programa \n"
            + "El comando que permite eliminar la Oferta de un Programa es: ELIMINAROFERTAPROGRAMA \n"
            + "parametros: ELIMINAROFERTAPROGRAMA [id_ofertaPrograma]\n"
            + "\n"

            + "REGISTRARBOLETAINSCRIPCION \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Registrar Boleta de Inscripcion \n"
            + "El comando que permite registrar una Boleta de Inscripcion es: REGISTRARBOLETAINSCRIPCION \n"
            + "parametros: REGISTRARBOLETAINSCRIPCION [id_estudiante, boolPago, fecha_fin]\n"
            + "Si BOOLPAGO = 1 => PAGO AL CONTADO\n"
            + "Si BOOLPAGO = 2 => PLAN DE PAGO DE 8 CUOTAS\n"
            + "\n"
            + "OBTENERBOLETAINSCRIPCION \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener Boleta Inscripcion\n"
            + "El comando que permite obtener una Boleta de Inscripcion es: OBTENERBOLETAINSCRIPCION \n"
            + "parametros: OBTENERBOLETAINSCRIPCION [id_planPago]\n"
            + "\n"
            + "OBTENERBOLETASINSCRIPCIONES \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtenrer Boletas de Inscripcion\n"
            + "El comando que permite obtener todas las Boletas de Inscripcion es: OBTENERBOLETASINSCRIPCIONES \n"
            + "parametros: OBTENERBOLETASINSCRIPCIONES\n"
            + "\n"
            + "ELIMINARBOLETAINSCRIPCION \n"
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Convalidacion \n"
            + "El comando que permite elimminar una Boleta de Inscripcion es: ELIMINARBOLETAINSCRIPCION \n"
            + "parametros: ELIMINARBOLETAINSCRIPCION [id_boletaInscripcion]\n"
            + "\n"
            //14
            + "OBTENERCUOTAS \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Obtener Cuotas\n"
            + "El comando que permite obtener las Cuotas de un Plan de Pago es: OBTENERCUOTAS \n"
            + "parametros: OBTENERCUOTAS [id_planPago]\n"
            + "\n"
            + "ELIMINARCUOTA \n"
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Cuota\n"
            + "El comando que permite eliminar una Cuota es: ELIMINARCUOTA \n"
            + "parametros: ELIMINARCUOTA [id_cuota]\n"
            + "\n"
            //15
            + "MODIFICARCRONOGRAMAMODULO \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Modificar Cronograma Modulo\n"
            + "El comando que permite modificar el Cronograma de un Modulo es: MODIFICARCRONOGRAMAMODULO \n"
            + "parametros: MODIFICARCRONOGRAMAMODULO [id, fecha_inicio, fecha_fin, id_ofertaProgram]\n"
            + "\n"
            + "ELIMINARCRONOGRAMAMODULO \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Eliminar Cronograma de un Modulo \n"
            + "El comando que permite eliminar el Cronograma de un Modulo es: ELIMINARCRONOGRAMAMODULO \n"
            + "parametros: ELIMINARCRONOGRAMAMODULO [id_cronogramaModulo]\n"
            + "\n"
           
            
            + "REPORTEUSUARIOS \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Reporte de Usuarios\n"
            + "El comando que permite visualizar el Reporte de la Cantidad de Usuarios es: REPORTEUSUARIOS \n"
            + "parametros: REPORTEUSUARIOS\n"
            + "\n"
            + "REPORTEGANANCIAS \n" 
            + ">>>> Solo Administrador del Sistema\n"
            + "Reporte de Ganancias\n"
            + "El comando que permite visualizar el Reporte de las ganancias en cuanto a las inversiones es: REPORTEGANANCIAS \n"
            + "parametros: REPORTEGANANCIAS \n"
            + "\n" 
//22
            ;

   //1 
    public static final String HELP_REGISTRARADMINISTRADOR = "Registrar Administrador \n"
            + "\n"
            + "El comando que permite registrar un Administrador es: REGISTRARADMINISTRADOR \n"
            + "parametros: REGISTRARADMINISTRADOR[nombre, apellido, ci, telefono, correo]\n";
    public static final String HELP_OBTENERADMINISTRADOR = "Obtener Administrador \n"
            + "\n"
            + "El comando que permite obtener los datos de un Administrador es: HELP_OBTENERADMINISTRADOR \n"
            + "parametros: HELP_OBTENERADMINISTRADOR[id]\n";
    public static final String HELP_OBTENERADMINISTRADORES = "Obtener todos los Administradores \n"
            + "\n"
            + "El comando que permite obtener todos los Administradores es: OBTENERADMINISTRADORES \n"
            + "parametros: OBTENERADMINISTRADORES[]\n";
    public static final String HELP_ELIMINARADMINISTRADOR = "Eliminar Administrador \n"
            + "\n"
            + "El comando que permite Eliminar un Administrador es: ELIMINARADMINISTRADOR \n"
            + "parametros: ELIMINARADMINISTRADOR[id]\n";
    //3
    public static final String HELP_REGISTRARCLIENTE = "Registrar Cliente \n"
            + "\n"
            + "El comando que permite registrar un Cliente es: REGISTRARCLIENTE \n"
            + "parametros: REGISTRARCLIENTE[nombre, apellido, ci, telefono, correo]\n";
    public static final String HELP_OBTENERCLIENTE = "Obtener Cliente \n"
            + "\n"
            + "El comando que permite obtener los datos de un Cliente es: OBTENERCLIENTE \n"
            + "parametros: OBTENERCLIENTE[id]\n";
    public static final String HELP_OBTENERCLIENTES = "Obtener todos los Clientes \n"
            + "\n"
            + "El comando que permite obtener los datos de un Cliente es: OBTENERCLIENTES \n"
            + "parametros: OBTENERCLIENTES[]\n";
    public static final String HELP_ELIMINARCLIENTE = "Eliminar Cliente \n"
            + "\n"
            + "El comando que permite Eliminar un Cliente es: ELIMINARCLIENTE \n"
            + "parametros: ELIMINARCLIENTE[id]\n";
    //4
   
    public static final String HELP_REGISTRARPROGRAMA = "Registrar Programa \n"
            + "\n"
            + "El comando que permite registrar un Programa es: REGISTRARPROGRAMA \n"
            + "parametros: REGISTRARPROGRAMA[nombre,presupuesto, version, edicion, tipo, fecha_ela, fecha_apro]\n";
    public static final String HELP_OBTENERPROGRAMA = "Obtener Programa \n"
            + "\n"
            + "El comando que permite obtener los datos de un Programa es: OBTENERPROGRAMA \n"
            + "parametros: OBTENERPROGRAMA[id]\n";
    public static final String HELP_OBTENERPROGRAMAS = "Obtener Programas \n"
            + "\n"
            + "El comando que permite obtener un listado de todos los Programa es: OBTENERPROGRAMAS \n"
            + "parametros: OBTENERPROGRAMAS[]\n";
    public static final String HELP_ELIMINARPROGRAMA = "Eliminar Programa \n"
            + "\n"
            + "El comando que permite Eliminar un Programa es: ELIMINARPROGRAMA \n"
            + "parametros: ELIMINARPROGRAMA[id]\n";
    //7
    public static final String HELP_REGISTRARMODULO = "Registrar Modulo \n"
            + "\n"
            + "El comando que permite registrar un Modulo es: REGISTRARMODULO \n"
            + "parametros: REGISTRARMODULO[nombre, sigla, descripcion, costo, horas_a, horas_i]\n";
    public static final String HELP_OBTENERMODULO = "Obtener Modulo \n"
            + "\n"
            + "El comando que permite obtener los datos de un modulo es: OBTENERMODULO \n"
            + "parametros: OBTENERMODULO[id]\n";
    public static final String HELP_ELIMINARMODULO = "Eliminar Modulo \n"
            + "\n"
            + "El comando que permite Eliminar un Modulo es: ELIMINARMODULO \n"
            + "parametros: ELIMINARMODULO[id]\n";
       public static final String HELP_REGISTRARMODULOSPROGRAMA = "Registrar Modulos a un Programa \n"
            + "\n"
            + "El comando que permite registrar los Modulos de un Programa es: REGISTRARMODULOSPROGRAMA \n"
            + "parametros: REGISTRARMODULOSPROGRAMA[id_programa, id_modulo]\n";
    public static final String HELP_OBTENERMODULOSPROGRAMA = "Obtiene los Modulos de un Programa \n"
            + "\n"
            + "El comando que permite obtener los Modulos de un Programa es: OBTENERMODULOSPROGRAMA \n"
            + "parametros: OBTENERMODULOSPROGRAMA[id_programa]\n";
    //11
    public static final String HELP_REGISTRAROFERTAPROGRAMA = "Registrar Oferta de un Programa \n"
            + "\n"
            + "El comando que permite registrar la Oferta de un Programa es: REGISTRAROFERTAPROGRAMA \n"
            + "parametros: REGISTRAROFERTAPROGRAMA[fecha_inicio, fecha_fin, descripcion, id_programa]\n";
    
   
    public static final String HELP_REGISTRARNOTIFICACION = "Registrar Cuota \n"
            + "\n"
            + "El comando que permite registrar una Cuota es: REGISTRARCUOTA \n"
            + "parametros: REGISTRARCUOTA[fecha, monto, id_plan_pago]\n";

}
